import pathlib

root = pathlib.Path(__file__).resolve().parents[1] / "Assets" / "6.Scripts"


def transform(src, dst, reps):
    c = (root / src).read_text(encoding="utf-8")
    for old, new in reps:
        c = c.replace(old, new)
    (root / dst).write_text(c, encoding="utf-8")
    print("wrote", dst)


runtime_reps = [
    ("FurnaceSmeltingRuntime", "CookingRuntime"),
    ("FurnaceRow", "CookingRow"),
    ("NormalizeFurnaceId", "NormalizeStationId"),
    ("furnaceId", "stationId"),
    ("FurnaceId", "StationId"),
    ("FurnaceSmelterSave", "CookingStationSave"),
    ("furnaceSmelters", "cookingStations"),
    ("SmeltingRecipe", "CookingRecipe"),
    ("SmeltingRecipes", "CookingRecipes"),
    ("TickSmelting", "TickCooking"),
    ("GetSmeltingBonuses", "GetCookingBonuses"),
    ("AddSmeltingBarXp", "AddCookingFishXp"),
    ("TryApplyActiveWork", "TryApplyCookingActiveWork"),
    ("LogSmeltingBatchComplete", "LogCookingBatchComplete"),
    ("TryRollBonusBar", "TryRollBonusCooked"),
    ("IsSmelting", "IsCooking"),
    ("_isSmelting", "_isCooking"),
    ("SmeltProgressSeconds", "CookProgressSeconds"),
    ("_smeltProgressSeconds", "_cookProgressSeconds"),
    ("smeltProgressSeconds", "cookProgressSeconds"),
    ("TryStartSmelting", "TryStartCooking"),
    ("StopSmelting", "StopCooking"),
    ("CanStartSmelting", "CanStartCooking"),
    ("TryGetSmeltTimeEstimate", "TryGetCookTimeEstimate"),
    ("GetOrePerBar", "GetRawPerCooked"),
    ("OrePerBar", "RawPerCooked"),
    ("StoredOreItemId", "StoredRawItemId"),
    ("_storedOreItemId", "_storedRawItemId"),
    ("storedOreItemId", "storedRawItemId"),
    ("StoredOreAmount", "StoredRawAmount"),
    ("_storedOreAmount", "_storedRawAmount"),
    ("storedOreAmount", "storedRawAmount"),
    ("ReadyBarAmount", "ReadyCookedAmount"),
    ("_readyBarAmount", "_readyCookedAmount"),
    ("readyBarAmount", "readyCookedAmount"),
    ("ReadyBarItemId", "ReadyCookedItemId"),
    ("_readyBarItemId", "_readyCookedItemId"),
    ("readyBarItemId", "readyCookedItemId"),
    ("_activeOreItemId", "_activeRawItemId"),
    ("activeOreItemId", "activeRawItemId"),
    ("GetActiveOreItemId", "GetActiveRawItemId"),
    ("TryGetForOre", "TryGetForRaw"),
    ("TryDepositOre", "TryDepositRaw"),
    ("TryWithdrawAllOre", "TryWithdrawAllRaw"),
    ("TryCollectBars", "TryCollectCooked"),
    ("ValidateOreDeposit", "ValidateRawDeposit"),
    ("ApplyOreDeposit", "ApplyRawDeposit"),
    ("GetReadyBarItemId", "GetReadyCookedItemId"),
    ("Persistent furnace smelting", "Persistent cooking range processing"),
    ("scene furnaces unload", "scene cooking ranges unload"),
    ("furnace stations", "cooking stations"),
    ('"furnace"', '"cooking_range"'),
    ("Furnace finished smelting", "Cooking finished"),
    ('RegisterLootChange("Furnace"', 'RegisterLootChange("Cooking"'),
    ("That ore cannot be smelted here.", "That fish cannot be cooked here."),
    ("Collect furnace bars before adding ore.", "Collect cooked food before adding fish."),
    ("This furnace already holds a different ore type.", "This range already holds a different fish type."),
    ("You do not have that ore.", "You do not have that fish."),
    ("Could not remove ore from inventory.", "Could not remove fish from inventory."),
    ("No ore stored.", "No fish stored."),
    ("Stop smelting before removing ore.", "Stop cooking before removing fish."),
    ("Must remove bars first.", "Must collect cooked food first."),
    ("No bars ready.", "Nothing ready to collect."),
    ("No bar type configured.", "No cooked result configured."),
    ("recipe.BarItemId", "recipe.CookedItemId"),
    ("secondsPerBar", "secondsPerCooked"),
    ("barsRemaining", "portionsRemaining"),
    ("DefaultOrePerBar", "DefaultRawPerCooked"),
]

station_reps = [
    ("FurnaceSmelter", "CookingStation"),
    ("FurnaceSmeltingRuntime", "CookingRuntime"),
    ("furnaceId", "stationId"),
    ("FurnaceId", "StationId"),
    ("SmeltingRecipe", "CookingRecipe"),
    ("SmeltingRecipes", "CookingRecipes"),
    ("IsSmelting", "IsCooking"),
    ("SmeltProgressSeconds", "CookProgressSeconds"),
    ("ReadyBarAmount", "ReadyCookedAmount"),
    ("ReadyBarItemId", "ReadyCookedItemId"),
    ("HasPendingBars", "HasPendingCooked"),
    ("StoredOreItemId", "StoredRawItemId"),
    ("StoredOreAmount", "StoredRawAmount"),
    ("GetActiveOreItemId", "GetActiveRawItemId"),
    ("GetOrePerBar", "GetRawPerCooked"),
    ("CanStartSmelting", "CanStartCooking"),
    ("TryStartSmelting", "TryStartCooking"),
    ("StopSmelting", "StopCooking"),
    ("TryGetSmeltTimeEstimate", "TryGetCookTimeEstimate"),
    ("TryDepositOre", "TryDepositRaw"),
    ("TryCollectBars", "TryCollectCooked"),
    ("Furnace not ready.", "Cooking range not ready."),
    ("Scene furnace binding", "Scene cooking range binding"),
    ('"furnace"', '"cooking_range"'),
    ("FurnaceRow", "CookingRow"),
]

click_reps = [
    ("FurnaceClick", "CookingClick"),
    ("FurnaceSmelter", "CookingStation"),
    ("FurnaceUI", "CookingUI"),
    ("furnaceCollider", "rangeCollider"),
    ("IsFurnaceOpen", "IsCookingOpen"),
    ("smelter", "station"),
    (
        "MerchantClick.ForceCloseMerchantMode();",
        "MerchantClick.ForceCloseMerchantMode();\n        FurnaceClick.ForceClose();",
    ),
]

visual_reps = [
    ("FurnaceStageVisual", "CookingStageVisual"),
    ("FurnaceSmelter", "CookingStation"),
    ("furnace world sprite", "cooking range world sprite"),
    ("smelting", "cooking"),
    ("smelter", "station"),
    ("IsSmelting", "IsCooking"),
    ("ReadyBarAmount", "ReadyCookedAmount"),
]

bonus_reps = [
    ("SmeltingProficiencyBonuses", "CookingProficiencyBonuses"),
    ("smelting speed", "cooking speed"),
    ("make 2 bars instead of 1", "make 2 portions instead of 1"),
    ("DoubleBarChancePercent", "DoublePortionChancePercent"),
    ("doubleBar", "doublePortion"),
]

ui_reps = [
    ("FurnaceUI", "CookingUI"),
    ("FurnaceClick", "CookingClick"),
    ("FurnaceSmelter", "CookingStation"),
    ("SmeltingRecipe", "CookingRecipe"),
    ("SmeltingRecipes", "CookingRecipes"),
    ("SmeltingProficiencyBonuses", "CookingProficiencyBonuses"),
    ("ProcessingSkillType.Smelting", "ProcessingSkillType.Cooking"),
    ("GetSmeltingBonuses", "GetCookingBonuses"),
    ("_smelter", "_station"),
    ("smelter", "station"),
    ("FurnaceBlocked", "CookingBlocked"),
    ("LogFurnaceBlocked", "LogCookingBlocked"),
    ("FurnaceBarsContextTrigger", "CookingFoodContextTrigger"),
    ("FurnaceDepositContextTrigger", "CookingDepositContextTrigger"),
    ("FurnacePanel", "CookingPanel"),
    ("furnace interface", "cooking interface"),
    ("SmeltingLevelButton", "CookingLevelButton"),
    ("SmeltingXp", "CookingXp"),
    ("_smeltingLevelButton", "_cookingLevelButton"),
    ("_smeltingLevelButtonText", "_cookingLevelButtonText"),
    ("_smeltingXpFill", "_cookingXpFill"),
    ("_smeltingXpFillRt", "_cookingXpFillRt"),
    ("RefreshSmeltingLevelButton", "RefreshCookingLevelButton"),
    ("RefreshSmeltingXpBar", "RefreshCookingXpBar"),
    ("BuildSmeltingXpBar", "BuildCookingXpBar"),
    ("OnSmeltingLevelClicked", "OnCookingLevelClicked"),
    ("RebuildOrePicker", "RebuildFishPicker"),
    ("HideOrePicker", "HideFishPicker"),
    ("_orePickerRoot", "_fishPickerRoot"),
    ("OrePicker", "FishPicker"),
    ("CreateOrePicker", "CreateFishPicker"),
    ("OnOreClearClicked", "OnFishClearClicked"),
    ("RefreshOreClearButton", "RefreshFishClearButton"),
    ("_oreClearButton", "_fishClearButton"),
    ("_oresButton", "_fishButton"),
    ("_barsButton", "_cookedButton"),
    ("_oreIcon", "_fishIcon"),
    ("_barIcon", "_cookedIcon"),
    ("_oreAmountText", "_fishAmountText"),
    ("_barAmountText", "_cookedAmountText"),
    ("CollectBars", "CollectCooked"),
    ("TryCollectBars", "TryCollectCooked"),
    ("ReadyBarAmount", "ReadyCookedAmount"),
    ("ReadyBarItemId", "ReadyCookedItemId"),
    ("StoredOreAmount", "StoredRawAmount"),
    ("StoredOreItemId", "StoredRawItemId"),
    ("IsSmelting", "IsCooking"),
    ("SmeltProgressSeconds", "CookProgressSeconds"),
    ("TryStartSmelting", "TryStartCooking"),
    ("StopSmelting", "StopCooking"),
    ("CanStartSmelting", "CanStartCooking"),
    ("TryGetSmeltTimeEstimate", "TryGetCookTimeEstimate"),
    ("FormatSmeltDuration", "FormatCookDuration"),
    ("GetOrePerBar", "GetRawPerCooked"),
    ("TryDepositOre", "TryDepositRaw"),
    ("TryWithdrawAllOre", "TryWithdrawAllFish"),
    ("GetActiveOreItemId", "GetActiveRawItemId"),
    ("TryGetForOre", "TryGetForRaw"),
    ("IsSmeltableOre", "IsCookableRaw"),
    ("Collect furnace bars before smelting.", "Collect cooked food before cooking again."),
    (
        "Requires at least {orePerBar} ores to smelt into a bar.",
        "Requires at least {rawPerCooked} fish to cook one portion.",
    ),
    ("orePerBar", "rawPerCooked"),
    (
        "The furnace converts ore into metal bars over time.",
        "The cooking range turns raw fish into cooked food over time.",
    ),
    (
        "Deposit ore, press Smelt, and wait for bars to finish. Collect bars before adding new ore or starting another batch.",
        "Deposit fish, press Cook, and wait for food to finish. Collect cooked food before adding new fish or starting another batch.",
    ),
    (
        "Higher-tier ores take longer to smelt but grant more Smelting proficiency.",
        "Better fish take longer to cook but grant more Cooking proficiency.",
    ),
    ("Smelting time:", "Cooking time:"),
    (" ore (", " fish ("),
    (" bars)", " portions)"),
    (' bar"', ' portion"'),
    (' bars"', ' portions"'),
    ("SMELT", "COOK"),
    ("Smelting — Lv", "Cooking — Lv"),
    ("< Smelting: Lv", "< Cooking: Lv"),
    ("increased smelting speed", "increased cooking speed"),
    ("chance to make 2 instead of 1 bar", "chance to make 2 instead of 1 portion"),
    ('"Ores"', '"Fish"'),
    ('"Bars"', '"Cooked"'),
    ("No smeltable ore in inventory.", "No cookable fish in inventory."),
    ("ActiveSmelter", "ActiveStation"),
    ('CreateHeader(_root, "Furnace")', 'CreateHeader(_root, "Cooking Range")'),
    ('headerText.text = "Smelting"', 'headerText.text = "Cooking"'),
    ("DoubleBarChancePercent", "DoublePortionChancePercent"),
]

transform("Furnace/FurnaceSmeltingRuntime.cs", "Cooking/CookingRuntime.cs", runtime_reps)
transform("Furnace/FurnaceSmelter.cs", "Cooking/CookingStation.cs", station_reps)
transform("Furnace/FurnaceClick.cs", "Cooking/CookingClick.cs", click_reps)
transform("Furnace/FurnaceStageVisual.cs", "Cooking/CookingStageVisual.cs", visual_reps)
transform("Crafting/SmeltingProficiencyBonuses.cs", "Cooking/CookingProficiencyBonuses.cs", bonus_reps)
transform("Furnace/FurnaceUI.cs", "Cooking/CookingUI.cs", ui_reps)
