public enum EnduranceMinorNodeStatOption
{
    None = 0,

    EnduranceHealthFlat10 = 1,
    EnduranceArmourFlat10 = 2,
    EnduranceEnergyEfficiencyPercent2 = 3,
    EnduranceMaxHealthPercent2 = 4,
    EnduranceThornsDamagePercent5 = 5,
    EnduranceLifeRegenFlat1 = 6,
    EnduranceMagicResistFlat10 = 7,
    EnduranceCorruptionResistFlat10 = 8,
    EnduranceMaxGuardPercent5 = 9,
    EnduranceHeavyArmourMasteryArmourFlat10 = 10,
    EnduranceBastionDrPercent5WhileGuardActive = 11,
    EnduranceLightArmourMasteryManaFlat20 = 12,
    EnduranceParryChancePercent2_5 = 13,
    EnduranceGuardGainPercent5 = 14,
    EnduranceShieldBlockChancePercent5 = 15,
    EnduranceShieldBlockMitigationPercent5 = 16,
    EnduranceMediumArmourMasteryMagicResistFlat5 = 17,
    EnduranceParryMitigationPercent5 = 18,
    EnduranceMediumArmourMasteryCorruptionResistFlat5 = 19,
    EnduranceMediumArmourMasteryMoveSpeedPercent10 = 20,
    EnduranceSurvivorDrPercent5BelowHalfHp = 21,
    EnduranceHeavyArmourMasteryMaxHealthPercent5 = 22,
    EnduranceLightArmourMasteryMagicResistFlat10 = 23,
    EnduranceMaxGuardPercent10 = 24,
    EnduranceLightArmourMasteryManaRegenFlat3 = 25,
}
