public enum RangedMinorNodeStatOption
{
    None = 0,
    RangedDamagePercent3 = 1,
    RangedAttackSpeedPercent3 = 2,
    RangedCritChancePercent2 = 3,
    RangedMoveSpeedPercent5 = 4,
    MinRangedDamageFlat2 = 5,
    MaxRangedDamageFlat2 = 6,
    RangedDamageVsLowHpPercent10 = 7,
    RangedShockChancePercent5 = 8,
    RangedLightningDamagePercent10 = 9,
    RangedDamageVsShockedPercent10 = 10,
    RangedLightningDamagePercent4 = 11,
    RangedCritDamagePercent8 = 12,
    RangedMoveSpeedPercent10 = 13,
    MinionDamagePercent5 = 14,
    MinionMaxLifePercent10 = 15,
    RangedDamageWithMinionActivePercent10 = 16,
    RangedDamageVsDistantPercent5 = 17,
    RangedDamageVsDistantPercent10 = 18,
    RangedDamageWhenNoNearbyEnemyPercent5 = 19,
    RangedDamageWhenNoNearbyEnemyPercent10 = 20,
    RangedDamageVsFullHpPercent6 = 21,
    MinionDamagePercent8 = 22,
}
